### ISSUE TITLE
Add SqlConnection constructor for SqlConnectionStringBuilder directly

### ISSUE THREAD

**Issue by BeJoNe** [microsoft/referencesource#106]
Microsoft Connect has been retired so I file my request here:
For me, the SqlConnection constructors are missing the SqlConnectionStringBuilder.
I have to provide **new SqlConnection(builder.ConnectionString)** which is really weird and not straight forward?
Just allow **new SqlConnection(builder)** directly.

**Comment by marek-safar** [comment]
Please follow https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md for new API suggestions

**Comment by BeJoNe** [comment]
Thanks, done
https://github.com/dotnet/corefx/issues/37582
