### ISSUE TITLE
Why there are 4 dashes in comments instead of words?

### ISSUE THREAD

**Issue by Otaman** [microsoft/referencesource#111]
I was wondered to see ---- instead some words in code's documentation. The dashes make it harder to understand the comments.

For example:
https://github.com/microsoft/referencesource/blob/e0bf122d0e52a42688b92bb4be2cfd66ca3c2f07/mscorlib/system/threading/Tasks/Task.cs#L273

**Comment by KalleOlaviNiemitalo** [comment]
I guess Microsoft automatically censors swear words from public sources and "race" somehow ended up in the blacklist.

**Comment by KalleOlaviNiemitalo** [comment]
Duplicate of #68

**Comment by terrajobst** [comment]
Closed as duplicate of #68.
