### ISSUE TITLE
__DynamicallyInvokableAttribute

### ISSUE THREAD

**Issue by Backup-eric645** [microsoft/referencesource#112]
I know there is a class, a compiler symbol class, called `__DynamicallyInvokableAttribute`, in the .NET Framework. It has been decompiled on a Telerik tool.

I then wanted to use it in my projects.

Make that `__DynamicallyInvokableAttribute` non-`internal` to let me use it in my own projects.

It is defined at the Default Namespace in all assemblies in the .NET Framework.

The new version of the .NET framework should be called `4.8.1 Modification`.

**Comment by SamB** [comment]
That would actually be completely useless; [the source says](https://referencesource.microsoft.com/#mscorlib/system/reflection/assembly.cs):

```c#
// Each blessed API will be annotated with a "__DynamicallyInvokableAttribute".
// This "__DynamicallyInvokableAttribute" is a type defined in its own assembly.
// So the ctor is always a MethodDef and the type a TypeDef.
// We cache this ctor MethodDef token for faster custom attribute lookup.
// If this attribute type doesn't exist in the assembly, it means the assembly
// doesn't contain any blessed APIs.
 ```

So if it's not in *your* assembly, it won't do **anything**.

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
