### ISSUE TITLE
Creating LanguageIntegratedAttribute

### ISSUE THREAD

**Issue by Backup-eric645** [microsoft/referencesource#113]
I am creating something called `LanguageIntegratedAttribute` which allows on properties, fields, and methods.

The compiler has to check for properties, methods, and fields named `Value` with that attribute signed, in static classes.

After it is done, it has to assign values to these classes.

That will introduce direct use of global variables.

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
