### ISSUE TITLE
Get RegionInfo based on ISO codes and from ISO Codes

### ISSUE THREAD

**Issue by Ellerbach** [microsoft/referencesource#114]
So far, it's only possible to get a RegionInfo from its name. Would be great to get the RegionInfo from the ISO Codes. Something like:

```csharp
List<RegionInfo> regions = RegionInfo.FromISOCurrencySymbol("EUR");
```

What is missing as well is to get the ISO country number (ISO 3166-1) and the ISO currency number (ISO 4217). So properties like ```ISOCountryCodeNumber``` as well as ```ISOCurrencyCodeNumber``` and same as for the previous point, have a way to get all the RegionInfo based on those codes:

```csharp
RegionInfo france = RegionInfo.FromISOCountryCodeNumber(250);
List<RegionInfo> allEuroCountries = RegionInfo.FromISOCurrencyCodeNumber(978);
```

ISO Country Number: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
ISO currency number: https://en.wikipedia.org/wiki/ISO_4217

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
