### ISSUE TITLE
Where is the definition of "LOADER_APPLICATION_BASE" in AppDomainSetup.LoaderInformation?

### ISSUE THREAD

**Issue by dwanboweb** [microsoft/referencesource#116]
I try to build the miscrolib in  .net 4.8,But It makes error .Please tell me where are they defined?Thank you.
![123](https://user-images.githubusercontent.com/17172451/63255116-9a908400-c2a7-11e9-8d29-d5325e0c652c.png)

**Comment by KalleOlaviNiemitalo** [comment]
I imagine Microsoft preprocesses this source code with some unpublished program, before compiling. There is preprocessable code in [System.Data/fx/src/data/System/Data/ProviderBase/](https://github.com/microsoft/referencesource/tree/24a17c0c3b23ddeac0926acc13b13c54b650d3be/System.Data/fx/src/data/System/Data/ProviderBase) as well, and perhaps an older version in [System.Data/System/Data/ProviderBase/](https://github.com/microsoft/referencesource/tree/24a17c0c3b23ddeac0926acc13b13c54b650d3be/System.Data/System/Data/ProviderBase).

**Comment by terrajobst** [comment]
We generally make no effort to make the code in this repository buildable because it's just the subset of the .NET Framework code base that we license under MIT. This is another example of that.
