### ISSUE TITLE
Extending Validator in DataAnnotations

### ISSUE THREAD

**Issue by hanu412** [Microsoft/referencesource#12]
I need to perform certain custom validations. I want to use attribute based validations as we have in DataAnnotations but when a validation fails,I would like to return a custom exception object instead a string. Any tips/guidance on how can  I extend it?

**Comment by blackdwarf** [comment]
@hanu412  If you are having issues with the Full .NET Framework or .NET Runtime, the best way to file a bug is at Connect (http://connect.microsoft.com/VisualStudio) or through Product Support (https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.
