### ISSUE TITLE
Missing Reference Source Files (Part 2 - Javascript in System.Web.Extensions)

### ISSUE THREAD

**Issue by MichaelKetting** [microsoft/referencesource#121]
This is a follow-up issue to #96, created and resolved by @steveisok .

For better tracking, I've now created this issue to document the Javascript files missing in System.Web.Extensions:

MicrosoftAjax.js
MicrosoftAjaxApplicationServices.js
MicrosoftAjaxComponentModel.js
MicrosoftAjaxCore.js
MicrosoftAjaxGlobalization.js
MicrosoftAjaxHistory.js
MicrosoftAjaxNetwork.js
MicrosoftAjaxSerialization.js
MicrosoftAjaxTimer.js
MicrosoftAjaxWebForms.js
MicrosoftAjaxWebServices.js
Date.HijriCalendar.js
Date.UmAlQuraCalendar.js
MicrosoftAjax.debug.js
MicrosoftAjaxApplicationServices.debug.js
MicrosoftAjaxComponentModel.debug.js
MicrosoftAjaxCore.debug.js
MicrosoftAjaxGlobalization.debug.js
MicrosoftAjaxHistory.debug.js
MicrosoftAjaxNetwork.debug.js
MicrosoftAjaxSerialization.debug.js
MicrosoftAjaxTimer.debug.js
MicrosoftAjaxWebForms.debug.js
MicrosoftAjaxWebServices.debug.js
Date.HijriCalendar.debug.js
Date.UmAlQuraCalendar.debug.js
MicrosoftAjax.js
MicrosoftAjax.debug.js
MicrosoftAjaxCore.js
MicrosoftAjaxCore.debug.js
MicrosoftAjaxWebForms.js
MicrosoftAjaxWebForms.debug.js

It would be much appriciated if those could be added as well. 

Thanks, Michael

**Comment by danmosemsft** [comment]
@steveisok is it possible for you to throw these up as well?

**Comment by MichaelKetting** [comment]
@danmosemsft @steveisok Is there any news on this?

**Comment by MichaelKetting** [comment]
@danmosemsft @steveisok Is there any news on this?

**Comment by danmosemsft** [comment]
I dug them up, hopefully @steveisok can do this

**Comment by MichaelKetting** [comment]
@danmosemsft  Thank you, much appreciated!

**Comment by MichaelKetting** [comment]
@steveisok Do you have an idea when you could get to this. It would be much appriciated!

**Comment by MichaelKetting** [comment]
@danmosemsft, @steveisok: I haven't heard any updates yet. It would be really great if we could get an ETA on this.

**Comment by danmosemsft** [comment]
@MichaelKetting could you please review https://github.com/microsoft/referencesource/pull/143 and confirm it's complete as far as you can tell?

**Comment by MichaelKetting** [comment]
@danmosemsft Thank you! I already scheduled the review for sometime in the next couple of workdays.

**Comment by danmosemsft** [comment]
OK @MichaelKetting when you give us the ack then I'll merge it.
