### ISSUE TITLE
System.Net.Mail fails to handle MTAs with multiline SMTP greeting/banners

### ISSUE THREAD

**Issue by paulgregg** [microsoft/referencesource#123]
https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/System/net/System/Net/mail/smtpconnection.cs#L354

The Microsoft Mail diagnostic tools 'Test Inbound SMTP Email' at https://testconnectivity.microsoft.com/ crashes when talking to an SMTP Server that implements multiline SMTP Banner / Greeting messages - e.g. Postfix's postscreen http://www.postfix.org/POSTSCREEN_README.html#pregreet

This ticket is being filed after talking with the Microsoft engineer responsible for the above diagnostic platform - who noted that they were using .NET System.Net.Mail.

Tracing through the code, I'm filing this ticket against what I believe to be the source of the issue - and hopefully this it a relatively simple fix.

Technical details:
RFC5321 defines SMTP Server greeting as:

```
In ABNF, server responses are:
   Greeting       = ( "220 " (Domain / address-literal)
                  [ SP textstring ] CRLF ) /
                  ( "220-" (Domain / address-literal)
                  [ SP textstring ] CRLF
                  *( "220-" [ textstring ] CRLF )
                  "220" [ SP textstring ] CRLF )
```

smtpconnection.cs makes a connection to the server and then expects a single line response:
```
…
            responseReader = new SmtpReplyReaderFactory(pooledStream.NetworkStream);
…
            LineInfo info = responseReader.GetNextReplyReader().ReadLine();
```

In looking at the ReadLine() definition inside GetNextReplyReader() it is a simple wrapper around ReadLines() with an optional parameter of oneline=True

is the fix a simple change to make it .ReadLines() ?

**Comment by akoeplinger** [comment]
I'd recommend filing this at https://github.com/dotnet/runtime as this repository contains the read-only reference source code for the .NET Framework and is not used to track bugs.

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
