### ISSUE TITLE
WebResponse object leak in `GetXmlReader` method

### ISSUE THREAD

**Issue by nekobul** [microsoft/referencesource#124]
https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/System.ServiceModel/System/ServiceModel/Description/MetadataExchangeClient.cs#L813

If the input `response` object contains invalid XML, the invocation of `reader.MoveToContent` method can lead to an exception and the response object will not be properly disposed. One possible fix would be to wrap the reading part in try/catch block like the following:

```c#
            internal static XmlReader GetXmlReader(HttpWebResponse response, long maxMessageSize, XmlDictionaryReaderQuotas readerQuotas)
            {
                readerQuotas = readerQuotas ?? EncoderDefaults.ReaderQuotas;
                XmlReader reader = XmlDictionaryReader.CreateTextReader(
                    new MaxMessageSizeStream(response.GetResponseStream(), maxMessageSize),
                    EncodingHelper.GetDictionaryReaderEncoding(response.ContentType),
                    readerQuotas,
                    null);

                try
                {
                  reader.Read();
                  reader.MoveToContent();
                }
                catch
                {
                  response.Dispose();
                  throw;
                }

                return reader;
            }
```

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
