### ISSUE TITLE
Outdated redirect comments

### ISSUE THREAD

**Issue by HugoRoss** [microsoft/referencesource#125]
> For issues regarding functionality, please use the following resources:
> 
> * BCL. https://github.com/dotnet/corefx
> * ASP.NET. https://github.com/aspnet/home
> * Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
> 

The comment in this edit field contains an outdated link to BCL, if opened one is redirected from "https://github.com/dotnet/corefx" (old, does not accept any pull requests anymore) to new "https://github.com/dotnet/runtime".

**Comment by terrajobst** [comment]
Good point, fixed
