### ISSUE TITLE
Incorrect RFC references in comment about HTTP Headers

### ISSUE THREAD

**Issue by jafreck** [microsoft/referencesource#128]
https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/System/net/System/Net/WebHeaderCollection.cs#L1232

RFC 216 is "Telnet Access To UCSB's Online System". The RFC that defines HTTP Header syntax is RFC 2616 "Hypertext Transfer Protocol -- HTTP/1.1".

https://tools.ietf.org/html/rfc2616

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
