### ISSUE TITLE
GetSexagenaryYear is based on Lunisolar Date instead of Sexagenary Date

### ISSUE THREAD

**Issue by samlishen** [microsoft/referencesource#129]
The GetSexagenaryYear use Lunisolar Date to determine the Sexagenary Year. However, Sexagenary Calendar has different "New Year" as Lunisolar Calendar. The Sexagenary "New Year" should be Lichun(Feb. 4th/3rd) instead of Lunisolar New Year.

You can find reference document on Wikipedia(https://en.wikipedia.org/wiki/Sexagenary_cycle#Sexagenary_months).

https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/mscorlib/system/globalization/eastasianlunisolarcalendar.cs#L53

**Comment by terrajobst** [comment]
This repository does not accept feature requests or bug reports. To submit those, you need to go elsewhere:

* [.NET Framework](https://developercommunity.visualstudio.com/dotnet)
* [.NET Core](https://github.com/dotnet/core)
