### ISSUE TITLE
TotalRowCount is off when using EF6 EntityDataSource + GridView

### ISSUE THREAD

**Issue by ojosdegris** [Microsoft/referencesource#13]
Hi,

I am not sure if that is right repo to file this bug, or may be it is not bug at all and I am just missing something.

I am using EF EntityDataSource with GridView and have autopage enabled. EDS is EntitySetName is set to a sql server view and I have AutoGenerateWhereClause="false"

My TotalRowCount is always off by some records, compared to query i can run by hand (ie `select count(*) from ( select * from myview ) a` ) and that is why when I click last page link in the pager it yields 0 records in the result and GridView do not render at all.

Have you ever see such behavior?

**Comment by blackdwarf** [comment]
@ojosdegris  If you are having issues with the Full .NET Framework or .NET Runtime, the best way to file a bug is at Connect (http://connect.microsoft.com/VisualStudio) or through Product Support (https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.
