### ISSUE TITLE
TryLoadRunnableWorkflowAsyncResult hides the InstanceCompleted error returned by the LoadInstance stored procedure

### ISSUE THREAD

**Issue by gesmaks** [Microsoft/referencesource#15]
The `ProcessSqlResult` method in the `TryLoadRunnableWorkflowAsyncResult` class (https://github.com/Microsoft/referencesource/blob/master/System.Activities.DurableInstancing/System/Activities/DurableInstancing/TryLoadRunnableWorkflowAsyncResult.cs) does not return an exception returned by the call to the `ProcessSqlResult` base method (the `LoadWorkflowAsyncResult.ProcessSqlResult` method).

The effect is that errors such as `System.Activities.DurableInstancing.CommandResult.InstanceCompleted` that are returned by the `[System.Activities.DurableInstancing].[LoadInstance]` stored procedure (it is called by the `[System.Activities.DurableInstancing].[TryLoadRunnableInstance]` procedure) are not returned by the `TryLoadRunnableWorkflowAsyncResult.ProcessSqlResult` method. This leads to a situation where the `WorkflowApplication.GetRunnableInstance` method called by user's code throws `InstanceNotReadyException` instead of `InstanceCompleteException`.

The problem is the `GetRunnableInstance` method throws `InstanceNotReadyException` also when there are valid instances in the `[System.Activities.DurableInstancing].RunnableInstances` table. It is enough to have one invalid instance in the `RunnableInstances` table (e.g. an instance that has its `IsCompleted` field set to `1`) to block retrieving process instances by the `GetRunnableInstance` method. Removing such invalid instance from the `RunnableInstances` table "unblocks" the other valid instances -- they are returned by the `GetRunnableInstance` method again.

I removed the "invalid" instance from the `RunnableInstances` table manually. Assuming that `GetRunnableInstance` method would throw the `InstanceCompleteException` there still would have to be some way remove such instance programatically from the runnable instances store. Perhaps the `[System.Activities.DurableInstancing]` stored procedures would need to do it in case when they find out an "invalid" instance in the `RunnableInstances` table.

In order to work this problem around I modified one of the `[System.Activities.DurableInstancing]` stored procedures -- `[LoadInstance]` -- to delete a completed instance from the `RunnableInstances` table.

**Comment by blackdwarf** [comment]
@gesmaks  If you are having issues with the Full .NET Framework or .NET Runtime, the best way to file a bug is at Connect (http://connect.microsoft.com/VisualStudio) or through Product Support (https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.
