### ISSUE TITLE
List adds a reset size method to reuse memory

### ISSUE THREAD

**Issue by sunliusi** [microsoft/referencesource#151]
A large list can lead to high memory usage. ObjectPool can solve this problem. Is it possible to allow external resizing to reuse memory.

just like:

public class List<T> : IList<T>, System.Collections.IList, IReadOnlyList<T>
        {
            private int _size;

            public void Reset(int size)
            {
                this._size = size;
            }
        }

**Comment by KalleOlaviNiemitalo** [comment]
@sunliusi, I don't think Microsoft intends to add any new features to .NET Framework. You can post this API proposal at <https://github.com/dotnet/runtime/issues/new/choose> and they can then consider it for .NET 7.

**Comment by KalleOlaviNiemitalo** [comment]
[Overview of .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/get-started/overview):

> .NET Framework 4.8 is the last version of .NET Framework, and no further versions will be released.

So, it's pretty clear that List\<T\>.Reset(int size) won't be added there.

**Comment by sunliusi** [comment]
Thanks for reminding. I'll close it. @KalleOlaviNiemitalo
