### ISSUE TITLE
Email Address Fails but Valid according to attribute

### ISSUE THREAD

**Issue by mthode88** [microsoft/referencesource#205]
I am working in .Net 8 and running into an email validation issue using the [EmailAddress] attribute.

Consider the following test:
```
[Fact]  
public void EmailAddressAttributeTest()  
{  
    var emailChecker = new System.ComponentModel.DataAnnotations.EmailAddressAttribute();  
    string email = "User Name user.name@consto.com";  
    bool isValid = emailChecker.IsValid(email);  
    Assert.False(isValid);  
}
```

This test fails when run. This type of email was then sent to our email server and failed to send because of it not being a valid email address.

For now I will add an additional validation to reject spaces in the email address but I feel this should be caught in the email address attribute validation.

**Comment by akoeplinger** [comment]
This is not the correct repository for .NET 8 issues, please file it in https://github.com/dotnet/runtime
