### ISSUE TITLE
Wrong absolute expiration is used

### ISSUE THREAD

**Issue by swcarter007** [Microsoft/referencesource#31]
The utcAbsoluteExpiration variable is not used in the method overloading on line 422.

/// <devdoc>
        /// <para>Inserts an object into the System.Web.Caching.Cache that has file or key dependencies and
        ///    expires at the value set in the <paramref name="absoluteExpiration"/> parameter.</para>
        /// </devdoc>
        public void Insert(string key, object value, CacheDependency dependencies, DateTime absoluteExpiration, TimeSpan slidingExpiration) {
            **DateTime utcAbsoluteExpiration = DateTimeUtil.ConvertToUniversalTime(absoluteExpiration);**
            ObjectCache.Insert(key, value, new CacheInsertOptions() {
                                                Dependencies = dependencies,
                                                **AbsoluteExpiration = absoluteExpiration,**
                                                SlidingExpiration = slidingExpiration
                                            });
        }

**Comment by klabranche** [comment]
I can confirm this is happening to me on two machines using this Insert signature.

**Comment by klabranche** [comment]
https://github.com/Microsoft/referencesource/blob/455f59f089ff2e96375e800c9b7866446f16cb30/System.Web/Cache/cache.cs#L425

**Comment by klabranche** [comment]
This appears to have been in the framework for a long time as is..... Not sure why it's now manifesting on some machines here and not others with the code we wrote for cache.insert not being changed itself since 2015.....  Must be something interrelated with a machine change....

**Comment by akoeplinger** [comment]
This is not the right repository to file issues about the bug, the referencesource repo is read-only.

@terrajobst can you please advise about where such issues should be filed? I think we should also add issue and pull request templates here which explain the distinction.

**Comment by terrajobst** [comment]
@swcarter007 

I suggest you file the issue in [aspnet/home](https://github.com/aspnet/Home/issues/new) repository. We only reference source infrastructure issues here.
