### ISSUE TITLE
System.Web.RegularExpressions is missing

### ISSUE THREAD

**Issue by Code-DJ** [microsoft/referencesource#33]
The classes in System.Web.RegularExpressions referenced in various System.Web classes are missing.

**Comment by akoeplinger** [comment]
@karelz I noticed this as well when I prototyped porting System.Web to Mono a few years ago. Who do we need to loop in to get these published?

Here's a list of classes:

```
System.Web.RegularExpressions.AspCodeRegex
System.Web.RegularExpressions.AspEncodedExprRegex
System.Web.RegularExpressions.AspExprRegex
System.Web.RegularExpressions.BindExpressionRegex
System.Web.RegularExpressions.BindItemExpressionRegex
System.Web.RegularExpressions.BindItemParametersRegex
System.Web.RegularExpressions.BindParametersRegex
System.Web.RegularExpressions.BrowserCapsRefRegex
System.Web.RegularExpressions.CommentRegex
System.Web.RegularExpressions.DataBindRegex
System.Web.RegularExpressions.DatabindExprRegex
System.Web.RegularExpressions.DirectiveRegex
System.Web.RegularExpressions.EndTagRegex
System.Web.RegularExpressions.EvalExpressionRegex
System.Web.RegularExpressions.ExpressionBuilderRegex
System.Web.RegularExpressions.FormatStringRegex
System.Web.RegularExpressions.GTRegex
System.Web.RegularExpressions.IncludeRegex
System.Web.RegularExpressions.LTRegex
System.Web.RegularExpressions.NonWordRegex
System.Web.RegularExpressions.RunatServerRegex
System.Web.RegularExpressions.ServerTagsRegex
System.Web.RegularExpressions.SimpleDirectiveRegex
System.Web.RegularExpressions.TagRegex
System.Web.RegularExpressions.TagRegex35
System.Web.RegularExpressions.TextRegex
System.Web.RegularExpressions.WebResourceRegex
```

**Comment by karelz** [comment]
@preetikr @richlander should be the right people

**Comment by steveisok** [comment]
I'm pretty far along porting System.Web to Mono and then to core.  I decompiled this assembly and I thought that would be enough, but the parser is blowing up on the DirectiveRegex.  The decomp is pretty ugly, so it would be great if this could be added.

There are more things missing too... But, I'll be happy if we could add this :-).

**Comment by karelz** [comment]
@richlander @preetikr ping?

**Comment by akoeplinger** [comment]
@steveisok let me know if you want to talk about the port, as I said I've done an initial attempt a few years ago so I'd be interested how things progressed since then :)

You can find me in https://gitter.im/mono/mono.

**Comment by Code-DJ** [comment]
See #96. Closing issue.
