### ISSUE TITLE
Thread-safe in Set_Value

### ISSUE THREAD

**Issue by kenteltest** [Microsoft/referencesource#37]
https://github.com/Microsoft/referencesource/blob/7de0d30c7c5ef56ab60fee41fcdb50005d24979a/mscorlib/system/threading/ThreadLocal.cs#L372 

If 2 threads enter this part of the code, there may be a situation where ts_finalizationHelper refers to an instance of one LinkedSlotVolatile object, and ts_slotArray refers to another instance

Although I may be wrong

**Comment by IharBury** [comment]
1. Both those fields are thread-static
2. This repo is not the right place to report bugs

**Comment by kenteltest** [comment]
1. Ooops. You are right
2. For the future, where I should do it?
Sorry

**Comment by IharBury** [comment]
Depends on the implementation which is affected by the bug. Try https://github.com/dotnet/core, for example.

**Comment by kenteltest** [comment]
Thanks
