### ISSUE TITLE
Reference Source is missing download link to 4.6.2 Source Code.

### ISSUE THREAD

**Issue by AraHaan** [Microsoft/referencesource#41]
It seems when trying to download 4.6.2 source code For Windows 7 that it fails with it not being found. I want to look into the implementation of it for hints to some things that fail on me in C++ (like ``K32EnumProcessModules`` failing with ``ERROR_INVALID_HANDLE`` when I use something like ``GetCurrentProccess()`` for the handle). 🤔

I am attempting to use that for checking for DLL injection that would terminate the process when it finds any dll not in a predefined process list (in this case not in a C++ ``vector``. However it fails like so and seems to eventually crash.

**Comment by SusLes** [comment]
Hi, Thank you for your report of the broken link.  The link is fixed now and confirmed working Live.
