### ISSUE TITLE
version numbers of assembly "System.ComponentModel.Annotations.d

### ISSUE THREAD

**Issue by emulic** [Microsoft/referencesource#42]
The version numbers of the assembly "System.ComponentModel.Annotations.dll" contained in all nugget package versions higher than 4.1.0  are messed up. I.e. the nuget packages 4.4.0 and 4.4.0 Preview2 contains assembly with the version 4.2.0. Package 4.3.0 contains assembly with the version 4.1.1 etc.
In some circumstances, this is causing following error at the runtime:
"Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

Repro steps:
1. Create a .NET Standard 1.4 class library project.
2. Use in some method of this library the following to deserialize some string:
var deserializedresult = JsonConvert.DeserializeObject(someSerializedObject, typeof(SomeType));
3. Create another .NET Framework 4.6.1 based class library (in my case this was an Azure FunctionsApp project)
4. Create in this library a method calling your method in the .NET Standard 1.4 class library project (see 2.)
5. I had installed packages Newtonsoft.Json 10.0.3, System.ComponentModel.Annotations 4.4.0 and System.ComponentModel.TypeConverter 4.3.0 in both projects.
The result is "Could not load file or assembly" error as described before.

If I install the version 4.1.0 of the package System.ComponentModel.Annotations in both projects, everything work as expected.

**Comment by terrajobst** [comment]
This repo only tracks infrastructure issues regarding the following items:

* Missing or outdated source in this repository
* Reference Source Browser (http://referencesource.microsoft.com/)
* Debugging the .NET Framework using Reference Source

For issues regarding functionality, please use the following resources:

* BCL. https://github.com/dotnet/corefx
* ASP.NET. https://github.com/aspnet/home
* Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
