### ISSUE TITLE
Reference source not in sync with object.cs

### ISSUE THREAD

**Issue by Iniii** [Microsoft/referencesource#45]
Should this repo replicate 

[Reference source](https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Input/Command/RoutedCommand.cs,0fce21dc7031e667)

?

If so, please keep it in sync. Currently it is not synced.

**Comment by CatGirlsAreLife** [comment]
ikr, just like the hell of trying to hack System.Reflection.Assembly to a assembly loaded from a zip file to return 'full path to zip file + \\ + path to assembly from within the zip'. With that this is my current but untested code for it https://github.com/Elskom/ZipAssembly/. Hopefully subclassing Assembly would actually force my 'Location' property to run.

**Comment by terrajobst** [comment]
This repo contains the subset of reference source that is MIT licensed. This omission is by-design.
