### ISSUE TITLE
Issue while signing TPM protected keys.

### ISSUE THREAD

**Issue by mathisharp** [Microsoft/referencesource#47]
# Issue while signing the TPM protected keys.

* Summary
    I can able to create the TPM protected key by passing the provider while creating the key below is the piece of code.
 CngKey.Create(CngAlgorithm.ECDsaP256, _keyName, 
                new CngKeyCreationParameters { KeyCreationOptions = CngKeyCreationOptions.MachineKey,Provider = new CngProvider("Microsoft Platform Crypto Provider") });

I can able to create the TPM protected key and open the key as well. The problem is while signing the key. Since the algorithm group is set to RSA instead of ECDSA. This algorithm group is set based on the provider at this point it is setting the wrong algorithm group internally.

* Reference Source Browser 
https://github.com/Microsoft/referencesource/blob/master/System.Core/System/Security/Cryptography/CngKey.cs

# Solution:
  If the algorithm group is set to appropriate group then the signing won't be a problem. Please update ASAP

**Comment by terrajobst** [comment]
This repo only tracks infrastructure issues regarding the following items:

* Missing or outdated source in this repository
* Reference Source Browser (http://referencesource.microsoft.com/)
* Debugging the .NET Framework using Reference Source

For issues regarding functionality, please use the following resources:

* BCL. https://github.com/dotnet/corefx
* ASP.NET. https://github.com/aspnet/home
* Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
