### ISSUE TITLE
Add pull request template so people stop filing PRs against this repo

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/referencesource#49]
Similar to the issue template we should add a PULL_REQUEST_TEMPLATE.md with some text about which PRs would be accepted in this repo, e.g. https://github.com/Microsoft/referencesource/pull/48 should go to corefx instead.

**Comment by karelz** [comment]
@terrajobst @richlander I think we should do this -- there are quite a few PRs we need to close: https://github.com/Microsoft/referencesource/pulls
Let's stop wasting contributors' time by discouraging such PRs.

I'll submit such PR unless @akoeplinger beats me to it ;)

**Comment by terrajobst** [comment]
Sounds good to me.
