### ISSUE TITLE
.NET Framework 4.7.2 update

### ISSUE THREAD

**Issue by jnm2** [Microsoft/referencesource#56]
What is the timeline for  https://referencesource.microsoft.com/ to be updated with net472 source? I wanted to see if I could answer [this person's question](https://github.com/Microsoft/dotnet-framework-early-access/issues/19#issuecomment-386721786).

**Comment by karelz** [comment]
@preetikr do we have timeline for releasing 4.7.2 reference source?

**Comment by preetikr** [comment]
We will have Reference sources for .NET 4.7.2 published in the next couple of days. 
Thanks, @NickCraver for the feedback - we will factor this in for the future.

**Comment by preetikr** [comment]
We now have reference sources for .NET Framework 4.7.2 published on [Microsoft Reference Source site](https://referencesource.microsoft.com/) and [GitHub](https://github.com/microsoft/referencesource. Thanks, for your patience.

**Comment by vchirikov** [comment]
@preetikr check https://github.com/Microsoft/referencesource/issues/63 please
