### ISSUE TITLE
Issue with the order when setting properties of client

### ISSUE THREAD

**Issue by milos92100** [Microsoft/referencesource#60]
https://github.com/Microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System/net/System/Net/mail/SmtpClient.cs#L267

If you set the credentials first and then say that you don't won't to use default credentials it sets the 
existing credentials to null which causes an authentication error. 
The _Credentials_ property should not be overridden by setting _UseDefaultCredentials_ to true which is by default.Choosing credentials should be done on sending.

**Working code:**
   ```c#
    let smtpClient = new SmtpClient()

    smtpClient.Host <- "smtp.gmail.com"
    smtpClient.Port <- 587
    smtpClient.EnableSsl <- true
    smtpClient.DeliveryMethod <- SmtpDeliveryMethod.Network
   
   //right order
    smtpClient.UseDefaultCredentials <- false
    smtpClient.Credentials <- new System.Net.NetworkCredential("***********", "**********")

    use mail = new MailMessage()
    mail.Body <- "Hello from Mocosha"
    mail.Subject <- "Test"
    mail.From <- new MailAddress("foo", "foo")
    mail.To.Add(new MailAddress("bar"))

    smtpClient.Send(mail)
```
   
**Not working code:**

 ```c#
   let smtpClient = new SmtpClient()

   smtpClient.Host <- "smtp.gmail.com"
   smtpClient.Port <- 587
   smtpClient.EnableSsl <- true
   smtpClient.DeliveryMethod <- SmtpDeliveryMethod.Network

  //problematic lines
  //different order
   smtpClient.Credentials <- new System.Net.NetworkCredential("***********", "**********")
   smtpClient.UseDefaultCredentials <- false
   
   use mail = new MailMessage()
   mail.Body <- "Hello from Mocosha"
   mail.Subject <- "Test"
   mail.From <- new MailAddress("foo", "foo")
   mail.To.Add(new MailAddress("bar"))

   smtpClient.Send(mail)
```

**Comment by terrajobst** [comment]
This repo only tracks infrastructure issues regarding the following items:

* Missing or outdated source in this repository
* Reference Source Browser (http://referencesource.microsoft.com/)
* Debugging the .NET Framework using Reference Source

For issues regarding functionality, please use the following resources:

* BCL. https://github.com/dotnet/corefx
* ASP.NET. https://github.com/aspnet/home
* Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
