### ISSUE TITLE
Validator.ValidateObject validateAllProperties argument misleading documentation.

### ISSUE THREAD

**Issue by alfredorevilla** [Microsoft/referencesource#61]
[Documentation ](https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/Validator.cs,407d4c16016f9715)for validateAllProperties states:

> true to validate all properties; otherwise, false.

However in order to validate not only all properties but also all validation attributes besides RequiredAttribute it must be set to true.

This issue should be present to TryValidateObject method too.

**Comment by terrajobst** [comment]
This repo only tracks infrastructure issues regarding the following items:

* Missing or outdated source in this repository
* Reference Source Browser (http://referencesource.microsoft.com/)
* Debugging the .NET Framework using Reference Source

For issues regarding functionality, please use the following resources:

* BCL. https://github.com/dotnet/corefx
* ASP.NET. https://github.com/aspnet/home
* Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
