### ISSUE TITLE
XAML files are missing in Workflow Designer

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/referencesource#62]
The XAML Workflow Designer, which is located under the following hierarchy, cannot be compiled because several XAML files are missing.

`referencesource/System.Activities.Presentation/System.Activities.Presentation/System/Activities/Presentation/`

The corresponding.xaml.cs files are available, but the actual xaml files are completely missing. Could these be added because the code is an incomplete version of the Workflow Designer.

**Comment by terrajobst** [comment]
This was fixed with #100
