### ISSUE TITLE
Regarding adding a custom column in datareader

### ISSUE THREAD

**Issue by slvmaurya** [Microsoft/referencesource#70]
Hi,

I have a requirement to pull data from Excel file into a datareader.
M
Am able to achieve it but in addition to that I want to have a additional column which has auto increment record no based on no. Of records present in the Excel.

I can't datatable for this scenario because am getting huge data from Excel file which can't be loaded into a datatable and push it into database.

So while I had used **Row_Number()** in the Ms access query while pulling data from the file but it didn't worked for me. 
Please suggest a approach so that it can solve my issue.

**Comment by terrajobst** [comment]
This repo only tracks infrastructure issues regarding the following items:

* Missing or outdated source in this repository
* Reference Source Browser (http://referencesource.microsoft.com/)
* Debugging the .NET Framework using Reference Source

For issues regarding functionality, please use the following resources:

* BCL. https://github.com/dotnet/corefx
* ASP.NET. https://github.com/aspnet/home
* Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
