### ISSUE TITLE
Add links to code on GitHub

### ISSUE THREAD

**Issue by hickford** [Microsoft/referencesource#8]
It would be neat if every page on the reference source site had a link to the corresponding file on GitHub (dotnet/coreclr or dotnet/corefx)

1. http://referencesource.microsoft.com/#mscorlib/system/collections/generic/icollection.cs
2. https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/ICollection.cs

**Comment by blackdwarf** [comment]
@hickford this repo should not be tracking issues and we will disable issues tracking now. For coreclr/corefx issues please file the issue on those repos.  If you are having issues with the Full .NET Framework or .NET Runtime, the best way to file a bug is at Connect (http://connect.microsoft.com/VisualStudio) or through Product Support (https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.
