### ISSUE TITLE
Repo Link: http:// -> https://

### ISSUE THREAD

**Issue by NickCraver** [Microsoft/referencesource#87]
The setting for the repo here (home link: https://github.com/Microsoft/referencesource) has the website site as `http://referencesource.microsoft.com/` when everything has moved to `https://` now. Can we please update this setting to https://referencesource.microsoft.com/?

**Comment by jakesays** [comment]
This isn't an issue because http:/ redirects to https:/

**Comment by jakesays** [comment]
Intercept it how?

**Comment by NickCraver** [comment]
I don't think it's necessary to get into "why https://?" here in the issue - that's just another copy of the discussion on the internet. sslstrip is one example (of many). But anyone in control of your connection or DNS (e.g. any public WiFi) can send the connection where they want. Or any malicious browser extensions (e.g. Chrome store buyouts), etc. The point is: there are lots of ways. If you're curious, search for http => https hijacking to see many examples.

The basics are: you can't have a secure connection to anything if first hopping through an insecure one. This redirect is no different.

**Comment by terrajobst** [comment]
> The setting for the repo here (home link: https://github.com/Microsoft/referencesource) has the website site as `http://referencesource.microsoft.com/` when everything has moved to `https://` now. Can we please update this setting to https://referencesource.microsoft.com/?

Which setting are you referring to?

**Comment by terrajobst** [comment]
After @NickCraver explained it to me, I was able to fix this :-)
