### ISSUE TITLE
Reliable WCF channel internal exception

### ISSUE THREAD

**Issue by zhangxin511** [Microsoft/referencesource#9]
Not sure if this is the right place to ask, but after enable reliable session, we see following errors almost once per month:

Exception object: 5795b954
Exception type:   System.Runtime.CallbackException
Message:          Async Callback threw an exception.
InnerException:   System.Runtime.Fx+InternalException, Use !PrintException 579182c4 to see more.
StackTrace (generated):
    SP       IP       Function
    4524E7D8 5A20EBB3 System_ServiceModel_Internals_ni!System.Runtime.AsyncResult.Complete(Boolean)+0x183
    4524E8EC 5A2129B4 System_ServiceModel_Internals_ni!System.Runtime.InputQueue`1+AsyncQueueReader[[System.__Canon, mscorlib]].Set(Item<System.__Canon>)+0x44
    4524E908 5A2116F9 System_ServiceModel_Internals_ni!System.Runtime.InputQueue`1[[System.__Canon, mscorlib]].Shutdown(System.Func`1<System.Exception>)+0x1d9
    4524E954 61CB8AFC System_ServiceModel_ni!System.ServiceModel.Channels.ReliableDuplexSessionChannel.ShutdownCallback(System.Object)+0xc
    4524E958 5A213492 System_ServiceModel_Internals_ni!System.Runtime.IOThreadScheduler+ScheduledOverlapped.IOCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)+0x72
    4524E994 5A213404 System_ServiceModel_Internals_ni!System.Runtime.Fx+IOCompletionThunk.UnhandledExceptionFrame(UInt32, UInt32, System.Threading.NativeOverlapped*)+0x44
    4524E9C0 6665387E mscorlib_ni!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)+0x6e

(inner)
0:000> !PrintException 579182c4 
Exception object: 579182c4
Exception type:   System.Runtime.Fx+InternalException
Message:          An unexpected failure occurred. Applications should not attempt to handle this error. For diagnostic purposes, this English message is associated with the failure: 'SetChannel is only valid in the NoChannel and ChannelOpening states'.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    4524E434 5A25573B System_ServiceModel_Internals_ni!System.Runtime.Fx.AssertAndThrow(System.String)+0x3b
    4524E444 61B92336 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableChannelBinder`1+ChannelSynchronizer[[System.__Canon, mscorlib]].SetChannel(System.__Canon)+0xda
    4524E478 61BA29BA System_ServiceModel_ni!System.ServiceModel.Channels.ClientReliableChannelBinder`1[[System.__Canon, mscorlib]].TryGetChannel(System.TimeSpan)+0x6a
    4524E4A0 61BB0A85 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableChannelBinder`1+ChannelSynchronizer+SyncWaiter[[System.__Canon, mscorlib]].TryGetChannel()+0x51
    4524E4E0 61BB0BAB System_ServiceModel_ni!System.ServiceModel.Channels.ReliableChannelBinder`1+ChannelSynchronizer+SyncWaiter[[System.__Canon, mscorlib]].TryWait(System.__Canon ByRef)+0x2b
    4524E4F0 61B92A89 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableChannelBinder`1+ChannelSynchronizer[[System.__Canon, mscorlib]].TryGetChannel(Boolean, Boolean, System.TimeSpan, System.ServiceModel.Channels.MaskingMode, System.__Canon ByRef)+0x2e9
    4524E54C 61B8F5F4 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableChannelBinder`1[[System.__Canon, mscorlib]].Send(System.ServiceModel.Channels.Message, System.TimeSpan, System.ServiceModel.Channels.MaskingMode)+0x1dc
    4524E5B0 61CB86F2 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableDuplexSessionChannel.OnSendHandler(System.ServiceModel.Channels.MessageAttemptInfo, System.TimeSpan, Boolean)+0xca
    4524E5FC 61CB0CA3 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableOutputConnection.InternalAddMessage(System.ServiceModel.Channels.Message, System.TimeSpan, System.Object, Boolean)+0x1af
    4524E684 61CB1012 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableOutputConnection.CompleteTransfer(System.TimeSpan)+0x5e
    4524E69C 61CB0A3E System_ServiceModel_ni!System.ServiceModel.Channels.ReliableOutputConnection.Close(System.TimeSpan)+0xb2
    4524E704 61CB7D95 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableDuplexSessionChannel.InternalCloseOutputSession(System.TimeSpan)+0x49
    4524E750 61CB70A0 System_ServiceModel_ni!System.ServiceModel.Channels.ReliableDuplexSessionChannel.OnCloseOutputSession(System.TimeSpan)+0xec
    4524E794 61CB90B3 System_ServiceModel_ni!System.ServiceModel.Channels.ClientReliableDuplexSessionChannel+DuplexClientReliableSession.CloseOutputSession(System.TimeSpan)+0x13
    4524E7A0 613D7DDB System_ServiceModel_ni!System.ServiceModel.Channels.ServiceChannel.DecrementActivity()+0xab
    4524E7D4 613C917D System_ServiceModel_ni!System.ServiceModel.Channels.ServiceChannel.HandleReceiveComplete(System.ServiceModel.Channels.RequestContext)+0xdd
    4524E808 613D0682 System_ServiceModel_ni!System.ServiceModel.Dispatcher.ChannelHandler.HandleReceiveComplete(System.ServiceModel.Channels.RequestContext)+0x32
    4524E840 613D050F System_ServiceModel_ni!System.ServiceModel.Dispatcher.ChannelHandler.EndTryReceive(System.IAsyncResult, System.ServiceModel.Channels.RequestContext ByRef)+0x2f
    4524E858 613D046B System_ServiceModel_ni!System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(System.IAsyncResult)+0x2b
    4524E870 613D042F System_ServiceModel_ni!System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(System.IAsyncResult)+0x3f
    4524E87C 5A2127EE System_ServiceModel_Internals_ni!System.Runtime.Fx+AsyncThunk.UnhandledExceptionFrame(System.IAsyncResult)+0x3e
    4524E8A0 5A20EB4F System_ServiceModel_Internals_ni!System.Runtime.AsyncResult.Complete(Boolean)+0x11f

**Comment by blackdwarf** [comment]
@zhangxin511  If you are having issues with the Full .NET Framework or .NET Runtime, the best way to file a bug is at Connect (http://connect.microsoft.com/VisualStudio) or through Product Support (https://support.microsoft.com/en-us/contactus?ws=support) if you have a contract.
