### ISSUE TITLE
X509Certificate2UI.SelectFromCollection is closing the application

### ISSUE THREAD

**Issue by guirsz** [Microsoft/referencesource#91]
https://github.com/dotnet/dotnet-api-docs/issues/1327

On a given client, when accessing the X509Certificate2UI.SelectFromCollection function the application is closing without even going through the error handling.

I'm using .NET Framework 4.5, and the problem happens on a machine with Windows 10 Pro, which has about 8 valid certificates.

I tried to use [SecurityCritical] attribute.

If use flag X509SelectionFlag.MultiSelection then works, but the application needs just one. Using X509SelectionFlag.SingleSelection doesn't work, and the application terminates.

**Comment by terrajobst** [comment]
This repo only tracks infrastructure issues regarding the following items:

* Missing or outdated source in this repository
* Reference Source Browser (http://referencesource.microsoft.com/)
* Debugging the .NET Framework using Reference Source

For issues regarding functionality, please use the following resources:

* BCL. https://github.com/dotnet/corefx
* ASP.NET. https://github.com/aspnet/home
* Everything else. https://connect.microsoft.com/VisualStudio/feedback/LoadSubmitFeedbackForm
