### ISSUE TITLE
⚠ HTTPS certificate on referencesource.microsoft.com expired again

### ISSUE THREAD

**Issue by jnm2** [Microsoft/referencesource#94]
![image](https://user-images.githubusercontent.com/8040367/52439588-e50b9980-2ae9-11e9-9390-aec1d0acbedb.png)

**Comment by karelz** [comment]
@mairaw @richlander @terrajobst @leecow who can help?

**Comment by karelz** [comment]
URL: https://referencesource.microsoft.com/

**Comment by KirillOsenkov** [comment]
Fixed now!
