### ISSUE TITLE
Missing Referencsource Files

### ISSUE THREAD

**Issue by steveisok** [microsoft/referencesource#96]
Tagging @karelz 

I've ported the 4.6 version of webforms into Mono and have noticed there are a bunch of missing files.  It would be great if you could get them added so that I can have a more complete port.

Here's the list:

asp_clientfiles
---------------
SmartNav.htm
SmartNav.js
WebForms.js
WebUIValidation.js

System.Web.RegularExpressions 
-----------------------------
ALL

System.Configuration
--------------------

**Files**

ConfigurationBuilder.cs
ConfigurationBuilderChain.cs
ConfigurationBuilderSettings.cs
ConfigurationBuildersSection.cs
ConfigurationStringConstants.cs
IInternalConfigurationBuilderHost.cs

**Resources**

System.Configuration.resx

System.Web
----------

**Files** 

Cache/AggregateEnumerator.cs
Cache/AspNetCache.cs
Cache/CacheCommon.cs
Cache/CacheGetOptions.cs
Cache/CacheInsertOptions.cs
Cache/CacheInternal.cs
Cache/CacheKeyComparer.cs
Cache/CacheMultiple.cs
Cache/CacheSingle.cs
Cache/CacheSizeMonitor.cs
Cache/CacheStoreProvider.cs
Cache/CacheExpires.cs
Cache/CacheUsage.cs
Cache/ExpiresBucket.cs
Cache/ExpiresEntityRef.cs
Cache/ExpiresEntry.cs
Cache/ExpiresPage.cs
Cache/ExpiresPageList.cs
Cache/UsageBucket.cs
Cache/UsageEntityRef.cs
Cache/UsageEntry.cs
Cache/UsageEntryLink.cs
Cache/UsagePage.cs
Cache/UsagePageList.cs
Globalization/IStringLocalizerProvider.cs
Globalization/ResourceFileStringLocalizerProvider.cs
Globalization/StringLocalizerProviders.cs
Hosting/ApplicationMonitors.cs
Hosting/ICustomLoaderHelperFunctions.cs
Hosting/CustomLoaderHelper.cs
Hosting/CustomLoaderAttribute.cs
ModelBinding/DisplayAttributeAdapter.cs
ModelBinding/MaxLengthAttributeAdapter.cs
ModelBinding/MinLengthAttributeAdapter.cs
State/ISessionStateModule.cs
Util/SecureHashCodeProvider.cs

**Resources**

GridView.js 
DetailsView.js  	
DetailsView.js 
TreeView.js 	 	
Menu.js	

System.Web.ApplicationServices
------------------------------

**Files**

System.Web.Security/IMembershipHelper.cs
System.Web.UI/KeyedList.cs
System.Web.UI/KeyedListEnumerator.cs

System.Web.DynamicData
----------------------

**Files**

Util/DisplayAttributeExtensions.cs
Util/StringLocalizerUtil.cs

**Resources**

System.Web.DynamicData.DynamicControl.bmp 
System.Web.DynamicData.DynamicDataManager.bmp 
System.Web.DynamicData.DynamicEntity.bmp 
System.Web.DynamicData.DynamicHyperLink.bmp 
System.Web.DynamicData.DynamicValidator.bmp 
System.Web.Resources.DynamicDataResources.resx

System.Web.DataVisualization
----------------------------

**Resources**

System.Web.UI.DataVisualization.Charting.ChartControl.ico
System.Web.UI.DataVisualization.Charting.Design.resx
System.Web.UI.DataVisualization.Charting.SR.resx

System.Web.Extensions
-----------------------

**Resources**

System.Web.Resources.AtlasWeb.resx
System.Web.Resources.ScriptLibrary.Res.debug.resx
System.Web.Resources.ScriptLibrary.Res.resx

**Comment by karelz** [comment]
@terrajobst @richlander who can help with this request?

**Comment by steveisok** [comment]
Ping - Is this possible?

**Comment by steveisok** [comment]
Ping + 1 :-)

**Comment by karelz** [comment]
@richlander @terrajobst ping?

**Comment by terrajobst** [comment]
I’ll setup a meeting with you and the owners. We need to fix this more broadly.

**Comment by karelz** [comment]
Sounds good!
cc @danmosemsft as FYI

**Comment by steveisok** [comment]
Did you guys have that meeting?  If so, what were the outcomes?

**Comment by karelz** [comment]
Nope, I don't think it happened. @terrajobst can you please set it up?

**Comment by steveisok** [comment]
@karelz @terrajobst Assuming this is going to be tough to get to, would having reflected versions of the files be a problem?  I'm all for getting the real files, but I also understand priorities. Thoughts?

**Comment by steveisok** [comment]
@karelz ping

**Comment by danmosemsft** [comment]
@steveisok the outcome of the meeting I think is that we don't have time in the foreseeable future to find the files and do the necessary cleaning to put them on reference source. You should have access to the official .NET Framework sources internally, can you use those? Possibly even offer a PR to the referencesource repo, optionally.

**Comment by steveisok** [comment]
@danmosemsft yes, I didn’t realize I had access.  Terrific!

**Comment by MichaelKetting** [comment]
I've also started to fiddle around with getting the reference sources to compile (for now, on Full Framework, but the intention is to put this on GitHub and get it to run on .NET Core) and found the following additional missing files (might be some other's I missed):

System.Web
* Compilation/WebObjectActivatorParseRecorder.cs

System.Web.Hosting
* Hosting/ApplicationMonitors.cs
* Hosting/AspNetMemoryMonitor.cs 

System.Web.Extensions
* DictionaryTypeResolver.cs

@steveisok 
The missing Cache-files:
The referenc sources include cacheexpires.cspp  and cacheusage.cspp which create some of the cache types from the first post. I'm not sure if there's actually a C# implementation of those.

**Comment by steveisok** [comment]
Good progress :-) 

https://github.com/microsoft/referencesource/pull/118

**Comment by danmosemsft** [comment]
Thanks @steveisok !

**Comment by MichaelKetting** [comment]
@steveisok Great, thanks a lot for this! May I ask if you had to reverse engineer or were you able to get the offical sources from Microsoft?

**Comment by steveisok** [comment]
@MichaelKetting They're official.

**Comment by MichaelKetting** [comment]
@steveisok 
Thanks again for organizing the file set. Am now much more complete when compiling System.Web.

I did notice that the JS-files for System.Web.Extensions are still missing:
MicrosoftAjax.js
MicrosoftAjaxApplicationServices.js
MicrosoftAjaxComponentModel.js
MicrosoftAjaxCore.js
MicrosoftAjaxGlobalization.js
MicrosoftAjaxHistory.js
MicrosoftAjaxNetwork.js
MicrosoftAjaxSerialization.js
MicrosoftAjaxTimer.js
MicrosoftAjaxWebForms.js
MicrosoftAjaxWebServices.js
Date.HijriCalendar.js
Date.UmAlQuraCalendar.js
MicrosoftAjax.debug.js
MicrosoftAjaxApplicationServices.debug.js
MicrosoftAjaxComponentModel.debug.js
MicrosoftAjaxCore.debug.js
MicrosoftAjaxGlobalization.debug.js
MicrosoftAjaxHistory.debug.js
MicrosoftAjaxNetwork.debug.js
MicrosoftAjaxSerialization.debug.js
MicrosoftAjaxTimer.debug.js
MicrosoftAjaxWebForms.debug.js
MicrosoftAjaxWebServices.debug.js
Date.HijriCalendar.debug.js
Date.UmAlQuraCalendar.debug.js
MicrosoftAjax.js
MicrosoftAjax.debug.js
MicrosoftAjaxCore.js
MicrosoftAjaxCore.debug.js
MicrosoftAjaxWebForms.js
MicrosoftAjaxWebForms.debug.js

Are you able to help with those, too?

Thanks, Michael

**Comment by Code-DJ** [comment]
@steveisok were you able to find these #33 as well? Thanks!

**Comment by steveisok** [comment]
Yeah, although System.Web.RegularExpressions is a bit "interesting" ;-)

https://github.com/microsoft/referencesource/tree/master/regexes
